input_data_path: "data/raw/heart.csv"
output_model_path: "models/model.pkl"
output_transformer_path: "models/transformer.pkl"
metric_path: "models/metrics.json"
splitting_params:
  train_size: 0.7
  random_state: 2
train_params:
  model_type: "XGBClassifier"
  model_params: {
    max_depth: 8,
    min_child_weight: 2
  }
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
    - "ca"
  target_col: "target"