apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  labels:
    app: online-inference-probes
spec:
  containers:
    - name: online-inference-probes
      image: yashinrostislav/online_inference:v2
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 100
        periodSeconds: 10